cabal-version:      2.4
name:               saas-handson-solution
version:            0.1.0.0
synopsis:           HaskellとServantで作るtoB SaaSハンズオン教材の解答例
build-type:         Simple

library
    hs-source-dirs:   src
    exposed-modules:  Api
                    , Server
                    , Health.Api
                    , Health.Server
                    , Health.Types
                    , User.Api
                    , User.Server
                    , User.Types
    build-depends:    base >=4.14 && <5
                    , servant-server
                    , warp
                    , aeson
                    , text
    default-language: Haskell2010

executable saas-handson-solution
    hs-source-dirs:   app
    main-is:          Main.hs
    ghc-options:      -threaded
    build-depends:    base >=4.14 && <5
                    , saas-handson-solution
                    , warp
    default-language: Haskell2010

test-suite unit
    type:               exitcode-stdio-1.0
    hs-source-dirs:     test/unit
    main-is:            Spec.hs
    other-modules:      Health.HealthSpec
                    , User.UserSpec
    build-depends:      base >=4.14 && <5
                      , saas-handson-solution
                      , hspec
                      , servant-server
    build-tool-depends: hspec-discover:hspec-discover
    default-language:   Haskell2010

test-suite integration
    type:               exitcode-stdio-1.0
    hs-source-dirs:     test/integration
    main-is:            Spec.hs
    other-modules:      Health.HealthSpec
                    , User.UserSpec
    build-depends:      base >=4.14 && <5
                      , saas-handson-solution
                      , hspec
                      , hspec-wai
                      , hspec-wai-json
                      , servant-server
                      , wai
                      , aeson
                      , bytestring
    build-tool-depends: hspec-discover:hspec-discover
    default-language:   Haskell2010
